theme: p2pparis
baseURL: https://p2p.paris
title: Paris P2P (& Cryptography)

languageCode: en
DefaultContentLanguage: en
defaultContentLanguageInSubdir: true

languages:
  en:
    languageName: English
    params:
      locale: en_GB
      default_description: The Parisian community interested in P2P & Cryptography technologies
    menu:
      main:
        - name: About
          url: "#about"
          weight: -100
        - name: Call for proposal
          url: "#call-for-proposal"
          weight: -90
        - name: Events
          url: "#events"
          weight: -80
        - name: Meetup
          url: "#meetup"
          weight: -70
        - name: Discord
          url: "#discord"
          weight: -60
        - name: Github
          url: "#github"
          weight: -50
        - name: Contact
          url: "#contact"
          weight: -40
  fr:
    languageName: French
    params:
      locale: fr_FR
      default_description: La communauté parisienne intéréssée par les technologies P2P et la Cryptographie
    menu:
      main:
        - name: À propos
          url: "#about"
          weight: -100
        - name: Envoyez vos sujets
          url: "#call-for-proposal"
          weight: -90
        - name: Évènements
          url: "#events"
          weight: -80
        - name: Meetup
          url: "#meetup"
          weight: -70
        - name: Discord
          url: "#discord"
          weight: -60
        - name: Github
          url: "#github"
          weight: -50
        - name: Contact
          url: "#contact"
          weight: -50

params:
  default_featured_image: /img/paris_p2p_thumbnail.jpg
  googleAnalyticsId: UA-124224137-5
